### ISSUE TITLE
Erro ao executar testes de unidade

### ISSUE THREAD

**Issue by caetanoharyon** [agaboduarte/Cielo-API-3.0#2]
Primeiramente obrigado pela iniciativa. Estou migrando os sistemas da empresa onde trabalho e o projeto de vocês vão me ajudar muito a entender a nova Api.

Bom, baixei o projeto, instalei as dependências, e ao rodar os testes isto ocorreu. Sabem o que pode ser? Teria algo a ver com certificados?

![cielo](https://cloud.githubusercontent.com/assets/6277837/17954995/dc65aa7e-6a4c-11e6-90fe-9ffad6bf9766.png)

**Comment by caetanoharyon** [comment]
Complementando: Executei os testes tanto com os meus dados de MerchantId e MerchantKey, quanto com o de vocês. Também alterei para utilizar CieloEnvironment.Sandbox na classe CieloApi.

**Comment by agabopinho** [comment]
Opa Haryon, tudo bem?

Obrigado pelo feedback!

Esse erro acontece comigo por causa da versão do .net framework que não suportava a versão do TSL do servidor da Cielo (TSL 1.2 no caso) ou não está configurado adequadamente em System.Net.ServicePointManager.SecurityProtocol como nas versões do .net framewoek 4.5.*, que tem suporte mas não vem configurado por padrão.

Suporte TSL 1.2:
-  Versões .NET 4.5 e anteriores: Não há suporte
-  Versão do .NET 4.5.\* em diante: Há suporte mas não vem configurado para utilização por padrão
-  Versão do .NET 4.6.\* em diante: Há suporte e já vem configurado

Para corrigir o problema das versões 4.5.\* eu efetuei a atualização https://github.com/agaboduarte/Cielo-API-3.0/commit/a3e5765208d0f0cd74cf6b0b5fd3dbdb1edacb1c, essa atualização também contêm o downgrade do projeto para a versão 4.5 do .net – que é a versão mínima para ser rodado.

Mais informações em: 
https://msdn.microsoft.com/en-us/library/system.net.securityprotocoltype(v=vs.110).aspx

Abs,
Ágabo D. de Pinho

**Comment by caetanoharyon** [comment]
Obrigado pelo rápido retorno. Baixei a última versão do projeto e os testes passaram.

**Comment by agabopinho** [comment]
Opa! :+1: 

Só para complementar, eu irei implementar em breve, dois novos métodos:
- Captura: para transações que foram apenas autorizadas
- Cancelamento total e parcial: para transações capturadas – cancelamento total e parcial, para autorizações – apenas cancelamento total.

**Comment by caetanoharyon** [comment]
Ótima notícia! Aguardo com expectativa.
