### ISSUE TITLE
Pagamento com Boleto

### ISSUE THREAD

**Issue by danillofratta** [agaboduarte/Cielo-API-3.0#7]
Olá camarada. Muito boa sua API.

Mas estou com dúvida de como integrar o pagamento com boleto.

Você tem algum exemplo? Como que faz para integrar o mesmo?

Abraço

**Comment by agabopinho** [comment]
Opa Danilo, 

Pagamento com boleto não foi implementado, apenas pagamento com cartão e recorrência. 

Abs

**Comment by danillofratta** [comment]
Fiz alterações no seu fonte para implementar pagamento no boleto e débito, e alguns outros retornos que estavam faltando. No ambiente de homologação esta funcionando, ainda não testei em produção. Se quiser me avisa que posso te retornar o projeto com as alterações que fiz. Abraço

**Comment by agabopinho** [comment]
Me manda que eu coloco na branch 'development'.

**Comment by danillofratta** [comment]
Não encontrei funcionalidade para fazer upload ou contato para te enviar. Aqui no post não deixou anexar.
