### ISSUE TITLE
Versao para Net.Core

### ISSUE THREAD

**Issue by pavini** [agaboduarte/Cielo-API-3.0#8]
Caros, primeiro parabéns pelo projeto!

Gostaria de saber se vão atualizar para funcionar com o .net core.

Abraços

**Comment by jmouradelo99** [comment]
Olá!!!
Tentei no Net Core 2.0 e tenha essa resposta.
Operation is not supported on this platform.

O que posso fazer?
Obrigado

**Comment by marceloleandro111** [comment]
Vocês tem consumo da Checkout Cielo?

**Comment by agabopinho** [comment]
@marceloleandro111, não tem integração com o checkout. Os métodos são direto para captura como consta nos testes:

- https://github.com/agabopinho/Integracao-Cielo-Api-3.0/blob/master/CieloTests/CieloApiTests.cs

não sei se ainda está tudo funcional, faz muito tempo que não utilizo essa lib.

**Comment by agabopinho** [comment]
Não estou dando manutenção nessa lib. Caso alguém atualize uma versão para net core, manda PR aqui, que eu valido e deixo disponível para todos!

**Comment by marceloleandro111** [comment]
A parte da API Ecommerce está funcional, não teve mudanças e o test funciona, mas estava procurando integração com a Checkout API para utilização do ambiente deles para autenticação/pagamento, porém, eles pedem um cadastro prévio e um prazo para envio da ID. Também em pesquisa não vi relatos de integração dos devs..

Att,
--
                 Marcelo Brito
               Analista de Sistemas
Pós-Graduado em Engenharia de Software

Contato: +55(81) 9174-9880
<http://imageshack.com/a/img537/9017/Xb93Kv.png>G-talk: marcelo.brito111@gmail.com
Skype  : marcelo_leandro111 / marcelo_leandro111@hotmail.com

<http://imageshack.com/a/img537/9798/2QPj7o.png>

<http://imageshack.com/a/img537/9798/2QPj7o.png>
"Você deve ser a própria mudança que deseja ver no mundo" (Mahatma Gandhi)
Call
Send SMS
Call from mobile
Add to Skype
You'll need Skype CreditFree via Skype

________________________________
De: Ágabo Pinho <notifications@github.com>
Enviado: quarta-feira, 5 de agosto de 2020 13:51
Para: agabopinho/Integracao-Cielo-Api-3.0 <Integracao-Cielo-Api-3.0@noreply.github.com>
Cc: marceloleandro111 <marcelo_leandro111@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [agabopinho/Integracao-Cielo-Api-3.0] Versao para Net.Core (#8)


@marceloleandro111<https://github.com/marceloleandro111>, não tem integração com o checkout. Os métodos são direto para captura com consta nos testes:

  *   https://github.com/agabopinho/Integracao-Cielo-Api-3.0/blob/master/CieloTests/CieloApiTests.cs

não sei se ainda está tudo funcional, faz muito tempo que não utilizo essa lib.
