### ISSUE TITLE
Referência de objeto não definida para uma instância de um objeto.

### ISSUE THREAD

**Issue by rodneyoliveira** [agaboduarte/Cielo-API-3.0#9]
Estou testando a solução em um controller, usando o mesmo código e está retornando Referência de objeto não definida para uma instância de um objeto, na linha:
 var returnTransaction = api.CreateTransaction(Guid.NewGuid(), transaction);

**Comment by agabopinho** [comment]
muito provável que vc não instanciou o **api**, não vejo outra alternativa com as informações que vc forneceu.
```cs
api = new CieloApi(CieloEnvironment.Sandbox, Merchant.Sandbox);
```

**Comment by rodneyoliveira** [comment]
public class HomeController : Controller
    {

        private ICieloApi api;
        private DateTime validExpirationDate;
        private DateTime invalidExpirationDate;

        public void ConfigEnvironment()
        {
            api = new CieloApi(CieloEnvironment.Sandbox, Merchant.Sandbox);
            validExpirationDate = new DateTime(DateTime.Now.Year + 1, 12,
1);
            invalidExpirationDate = new DateTime(DateTime.Now.Year - 1, 12,
1);
        }
        public ActionResult Index()
        {
            var customer = new Customer(name: "Fulano da Silva");

            var creditCard = new CreditCard(
                cardNumber: SandboxCreditCard.Authorized1,
                holder: "Teste Holder",
                expirationDate: validExpirationDate,
                securityCode: "123",
                brand: CardBrand.Visa);

            var payment = new Payment(
                amount: 150.00M,
                currency: Currency.BRL,
                installments: 1,
                capture: false,
                softDescriptor: "DOTNETPROJECT",
                creditCard: creditCard);

            /* store order number */
            var merchantOrderId = new Random().Next();

            var transaction = new Transaction(
                merchantOrderId: merchantOrderId.ToString(),
                customer: customer,
                payment: payment);

            var returnTransaction = api.CreateTransaction(Guid.NewGuid(),
transaction);

            return View();
        }


    }
}


Em seg, 29 de jul de 2019 às 20:42, Ágabo Pinho <notifications@github.com>
escreveu:

**Comment by agabopinho** [comment]
É isso mesmo. Vc não instanciou a variável api. Muda o nome do método ConfigEnvironment para HomeController que ele passará a ser o construtor da classe.

**Comment by rodneyoliveira** [comment]
Valeu!!!




Em ter, 30 de jul de 2019 às 11:02, Ágabo Pinho <notifications@github.com>
escreveu:
